name: Matrix Test
on:
  workflow_call:
    inputs:
      test_type: # 'test' or 'testacc'
        type: string
        required: true
      tf_log:
        type: string
        required: false
        default: ""
      # The branch, tag or SHA to checkout. When checking out the repository that
      # triggered a workflow, this defaults to the reference or SHA for that event.
      # Otherwise, uses the default branch.
      ref:
        type: string
        required: false
        default: ""
jobs:
  # run tests in a matrix with Terraform core versions
  test:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 90

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          - "1.11.*"
          - "1.12.*"
          - "1.13.*"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"
        id: go

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: ${{inputs.ref}}

      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Get dependencies
        run: |
          go mod download

      - name: TF unit tests
        if: "${{ inputs.test_type == 'test' }}"
        timeout-minutes: 5
        run: |
          TF_LOG=${{inputs.tf_log}} make test

      - name: TF acceptance tests
        if: "${{ inputs.test_type == 'testacc' }}"
        timeout-minutes: 60
        env:
          ITSI_HOST: ${{ secrets.ITSI_HOST }}
          ITSI_PORT: ${{ secrets.ITSI_PORT }}
          ITSI_ACCESS_TOKEN: ${{ secrets.ITSI_ACCESS_TOKEN }}

        run: |
          TF_LOG=${{inputs.tf_log}} make testacc
