name: Matrix Test
on:
  workflow_call:
    inputs:
      test_type: # 'test' or 'testacc'
        type: string
        required: true
jobs:
  # run acceptance tests in a matrix with Terraform core versions
  test:
    name: acc tests
    runs-on: ubuntu-latest
    timeout-minutes: 90

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        # list whatever Terraform versions here you would like to support
        terraform:
          - "1.7.*"
          - "1.8.*"
          - "1.9.*"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
        id: go

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Get dependencies
        run: |
          go mod download

      - name: TF unit tests
        if: "${{ inputs.test_type == 'test' }}"
        timeout-minutes: 5
        run: |
          make test

      - name: TF acceptance tests
        if: "${{ inputs.test_type == 'testacc' }}"
        timeout-minutes: 60
        env:
          ITSI_HOST: ${{ secrets.ITSI_HOST }}
          ITSI_PORT: ${{ secrets.ITSI_PORT }}
          ITSI_ACCESS_TOKEN: ${{ secrets.ITSI_ACCESS_TOKEN }}

        run: |
          make testacc
