name: Acceptance Tests
on:
  issue_comment:
    types: [created]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  testacc:
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/testacc')
    uses: ./.github/workflows/matrix_test.yaml
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    with:
      test_type: testacc
